create user notadez identified by secretmypass;
grant create session to notadez;/*autorização para o usuário se conectar com o banco*/

select username,
       authentication_type
  from dba_users
 where username = 'NOTADEZ'; /*da um select na tabela dba-users pra verificar se o usuario webapp foi criado*/

create tablespace data
   datafile 'C:\oracle\data.dbf' size 100M
   autoextend on;

alter user notadez
   default tablespace data
   temporary tablespace temp;

alter user notadez
   quota 100M on data; /* altera para ter 100 megas de dados*/

select username,
       default_tablespace,
       temporary_tablespace
  from dba_users
 where username = 'NOTADEZ'; /* verificar se o usuario webapp esta la, e qual o tablespace temporario*/

select tablespace_name,
       bytes,
       max_bytes
  from dba_ts_quotas
 where username = 'NOTADEZ'; /*VERIFICAR A QUOTA*/
/*ainda como admin vamos criar uma tabela*/

create table notadez.docente (
   id_docente    number generated by default as identity primary key,
   nome_docente  varchar2(100) not null,
   email_docente varchar2(100) unique,
   senha         varchar2(100) unique,
   created_at    date default current_date
)
tablespace data; /*regra para que cada espaço de tabela tenha um dado guardado, tipo NOT NULL*/

create table notadez.instituicoes (
   id_instituicao   number generated by default as identity primary key,
   nome_instituicao varchar2(100) not null
);

create table notadez.cursos (
   id_curso   number generated by default as identity primary key /*auto incremento*/,
   nome_curso varchar2(100) not null
);

create table notadez.cadastros /*associativa, para verificar cadastro*/ (
   id_cadastro    number generated by default as identity primary key,
   id_instituicao number,
   nome_docente   varchar2(100),
   id_curso       number,
      primary key ( id_cadastro,
                    id_instituicao,
                    nome_docente,
                    id_curso ),
   foreign key ( id_instituicao )
      references notadez.instituicoes ( id_instituicao ),
   foreign key ( nome_docente )
      references notadez.docentes ( nome_docente ),
   foreign key ( id_curso )
      references notadez.cursos ( id_curso )
);


create table notadez.disciplina (
   id_disciplina    number generated by default as identity primary key,
   nome_disciplina  varchar2(100) not null,
   sigla_disciplina varchar2(5),
   periodo          varchar2(50),
   peso_p1          float,
   peso_p2          float,
   peso_p3          float
);

create table notadez.turma (
   id_turma     number generated by default as identity primary key,
   nome_turma   varchar2(100) not null,
   local_aula   varchar2(100) not null,
   horario_aula varchar2(100) not null
);

create table notadez.dia (
   id_dia   number generated by default as identity primary key,
   nome_dia varchar2(20)
);
/*ID DIA ESTA SEPARADO PARA EVITAR REPETIÇÃO DE DIA*/

create table notadez.possui_disciplinas /*associativa*/ ( /*para organizar os dias e horarios, evitar repetição e dor de cabeça = (JOIN)*/
   id_turma      number not null,
   id_disciplina number not null,
   id_dia        number not null,
   primary key ( id_turma,
                 id_disciplina,
                 id_dia ),
   foreign key ( id_turma )
      references notadez.turma ( id_turma ),
   foreign key ( id_disciplina )
      references notadez.disciplina ( id_disciplina ),
   foreign key ( id_dia )
      references notadez.dia ( id_dia )
);

create table notadez.alunos /*asssociativa*/ ( /*pegar apenas a informação e qual a turma*/
   ra_aluno   number primary key, /*matricula do aluno, nao auto-incremento*/
   nome_aluno varchar2(100) not null
);

create table notadez.matricula ( /*associativa*/
   ra_aluno number not null,
   id_turma number not null,
   primary key ( ra_aluno,
                 id_turma ),
   foreign key ( ra_aluno )
      references notadez.alunos ( ra_aluno ),
   foreign key ( id_turma )
      references notadez.turma ( id_turma )
);

/*Tabela para relacionar disciplina com instituicao e curso*/
create table notadez.disciplina_instituicao (
   id_disciplina  number not null,
   id_instituicao number not null,
   id_curso       number not null,
   id_docente     number not null,
   primary key ( id_disciplina,
                 id_instituicao,
                 id_curso ),
   foreign key ( id_disciplina )
      references notadez.disciplina ( id_disciplina ),
   foreign key ( id_instituicao )
      references notadez.instituicoes ( id_instituicao ),
   foreign key ( id_curso )
      references notadez.cursos ( id_curso ),
   foreign key ( id_docente )
      references notadez.docente ( id_docente )
);

/*Tabela para relacionar turma com disciplina*/
create table notadez.turma_disciplina (
   id_turma      number not null,
   id_disciplina number not null,
   primary key ( id_turma,
                 id_disciplina ),
   foreign key ( id_turma )
      references notadez.turma ( id_turma ),
   foreign key ( id_disciplina )
      references notadez.disciplina ( id_disciplina )
);

/*Tabela de componentes de nota*/
create table notadez.componentes_nota (
   id_componente    number generated by default as identity primary key,
   id_disciplina    number not null,
   nome_componente  varchar2(100) not null,
   sigla_componente varchar2(10) not null,
   descricao        varchar2(200),
   foreign key ( id_disciplina )
      references notadez.disciplina ( id_disciplina )
);

/*Tabela de notas dos alunos*/
create table notadez.notas (
   id_nota         number generated by default as identity primary key,
   ra_aluno        number not null,
   id_turma        number not null,
   id_componente   number not null,
   valor_nota      number(5,2) not null,
   data_lancamento date default current_date,
   foreign key ( ra_aluno )
      references notadez.alunos ( ra_aluno ),
   foreign key ( id_turma )
      references notadez.turma ( id_turma ),
   foreign key ( id_componente )
      references notadez.componentes_nota ( id_componente ),
   unique ( ra_aluno,
            id_turma,
            id_componente )
);

/*Tabela de formula de nota final*/
create table notadez.formula_nota_final (
   id_formula    number generated by default as identity primary key,
   id_disciplina number not null,
   tipo_formula  varchar2(20) not null, /*aritmetica ou ponderada*/
   formula_text  varchar2(200),
   foreign key ( id_disciplina )
      references notadez.disciplina ( id_disciplina )
);

/*Tabela de auditoria de notas*/
create table notadez.auditoria_notas (
   id_auditoria  number generated by default as identity primary key,
   ra_aluno      number not null,
   id_componente number not null,
   valor_antigo  number(5,2),
   valor_novo    number(5,2),
   data_hora     timestamp default current_timestamp,
   id_docente    number not null,
   foreign key ( ra_aluno )
      references notadez.alunos ( ra_aluno ),
   foreign key ( id_componente )
      references notadez.componentes_nota ( id_componente ),
   foreign key ( id_docente )
      references notadez.docente ( id_docente )
);

/*Trigger para auditoria automatica - UPDATE*/
create or replace trigger notadez.trigger_auditoria_notas_update before
   update on notadez.notas
   for each row
begin
   insert into notadez.auditoria_notas (
      ra_aluno,
      id_componente,
      valor_antigo,
      valor_novo,
      id_docente
   ) values ( :old.ra_aluno,
              :old.id_componente,
              :old.valor_nota,
              :new.valor_nota,
              1 );
end;
/

/*Trigger para auditoria automatica - INSERT*/
create or replace trigger notadez.trigger_auditoria_notas_insert after
   insert on notadez.notas
   for each row
begin
   insert into notadez.auditoria_notas (
      ra_aluno,
      id_componente,
      valor_antigo,
      valor_novo,
      id_docente
   ) values ( :new.ra_aluno,
              :new.id_componente,
              null,
              :new.valor_nota,
              1 );
end;
/
