-- Autor: Bernardo Castro Brandão de Oliveira
-- Script para criação de usuário, tablespace, tabelas e triggers para aplicação NOTADEZ

-- ========================================
-- CRIAÇÃO DO USUÁRIO E CONCESSÃO DE PRIVILÉGIOS
-- ========================================
create user notadez identified by secretmypass; -- Cria usuário NOTADEZ com senha
grant connect, resource, create table, create view, create sequence, create trigger to notadez; -- Concede privilégios essenciais

-- Verifica se o usuário foi criado corretamente
select username, authentication_type 
from dba_users 
where username = 'NOTADEZ'; 

-- ========================================
-- CRIAÇÃO DE TABLESPACE
-- ========================================
create tablespace data 
datafile 'C:\app\Usuario\product\21c\oradata\XE\data.dbf' 
size 100M autoextend on; -- Cria tablespace "data" com autoextensão

-- Configura tablespace padrão e temporário do usuário
alter user notadez default tablespace data temporary tablespace temp;

-- Define quota de 100MB para o usuário no tablespace "data"
alter user notadez quota 100M on data;

-- Verifica configuração de tablespace do usuário
select username, default_tablespace, temporary_tablespace 
from dba_users 
where username = 'NOTADEZ'; 

-- Verifica quota de tablespace do usuário
select tablespace_name, bytes, max_bytes 
from dba_ts_quotas 
where username = 'NOTADEZ'; 

-- ========================================
-- CRIAÇÃO DAS TABELAS PRINCIPAIS
-- ========================================

-- Tabela de docentes
create table NOTADEZ.DOCENTES (
   ID_DOCENTE    number generated by default as identity primary key, -- PK auto-incremento
   NOME  varchar2(100) not null, -- Nome do docente
   EMAIL varchar2(100) unique, -- Email único
   SENHA varchar2(100) not null, -- Senha
   TELEFONE int, -- Telefone
   DATA_CADASTRO date default current_date -- Data de cadastro
)
tablespace data; -- Define tablespace para armazenamento

-- Tabela de turmas
CREATE TABLE notadez.turmas ( 
  id_turma NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  nome_turma VARCHAR2(100) NOT NULL, 
  horario_aula TIMESTAMP NOT NULL, -- Data e hora da aula
  local_aula VARCHAR2(100) NOT NULL, 
  dia_aula VARCHAR2(20) NOT NULL ); -- Dia da semana

-- Tabela de disciplinas
CREATE TABLE notadez.disciplinas ( 
  id_disciplina NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  sigla_disciplina VARCHAR2(20) NOT NULL, 
  nome_disciplina VARCHAR2(100) NOT NULL, 
  periodo DATE NOT NULL ); -- Data/Período da disciplina

-- Tabela de instituições
CREATE TABLE notadez.instituicoes ( 
  id_instituicao NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  nome_instituicao VARCHAR2(100) NOT NULL );

-- Tabela de cursos
CREATE TABLE notadez.cursos ( 
  id_curso NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  nome_curso VARCHAR2(100) NOT NULL, 
  id_instituicao NUMBER NOT NULL, 
  FOREIGN KEY (id_instituicao) REFERENCES notadez.instituicoes(id_instituicao) ); -- FK para instituição

-- Tabela de notas
CREATE TABLE notadez.notas ( 
  id_nota NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  id_turma NUMBER NOT NULL, 
  valor_nota NUMBER NOT NULL, 
  data_lancamento DATE NOT NULL, 
  FOREIGN KEY (id_turma) REFERENCES notadez.turmas(id_turma) ); -- FK para turma

-- Tabela de alunos
CREATE TABLE notadez.alunos ( 
  ra_aluno NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  nome_aluno VARCHAR2(100) NOT NULL );

-- Tabela de componentes de nota
CREATE TABLE notadez.componentes_nota ( 
  id_componente NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  id_disciplina NUMBER NOT NULL, 
  nome_componente VARCHAR2(100) NOT NULL, 
  descricao VARCHAR2(255) NOT NULL, 
  sigla_componente VARCHAR2(20) NOT NULL, 
  FOREIGN KEY (id_disciplina) REFERENCES notadez.disciplinas(id_disciplina) );

-- Tabela de fórmulas de nota final
CREATE TABLE notadez.formula_nota_final ( 
  id_formula NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  id_disciplina NUMBER NOT NULL, 
  tipo_formula VARCHAR2(50) NOT NULL, 
  peso_p1 NUMBER NOT NULL, 
  peso_p2 NUMBER NOT NULL, 
  peso_p3 NUMBER NOT NULL, 
  formula_text VARCHAR2(255) NOT NULL, 
  FOREIGN KEY (id_disciplina) REFERENCES notadez.disciplinas(id_disciplina) );

-- Tabela de auditoria de notas
CREATE TABLE notadez.auditoria_notas ( 
  id_auditoria NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  ra_aluno NUMBER NOT NULL,
  id_componente NUMBER NOT NULL, 
  id_docente NUMBER NOT NULL, 
  valor_antigo NUMBER NOT NULL, 
  valor_novo NUMBER NOT NULL, 
  data_hora TIMESTAMP NOT NULL, 
  FOREIGN KEY (ra_aluno) REFERENCES notadez.alunos(ra_aluno), 
  FOREIGN KEY (id_componente) REFERENCES notadez.componentes_nota(id_componente), 
  FOREIGN KEY (id_docente) REFERENCES notadez.docentes(id_docente) );

-- ========================================
-- TABELAS ASSOCIATIVAS (M:N)
-- ========================================

-- Cadastro de docentes em instituições
CREATE TABLE notadez.cadastro ( 
  id_docente NUMBER NOT NULL, 
  id_instituicao NUMBER NOT NULL, PRIMARY KEY (id_docente, id_instituicao), 
  FOREIGN KEY (id_docente) REFERENCES notadez.docentes(id_docente), 
  FOREIGN KEY (id_instituicao) REFERENCES notadez.instituicoes(id_instituicao) );

-- Matricula de alunos em turmas
CREATE TABLE notadez.matriculam ( 
  id_turma NUMBER NOT NULL, 
  ra_aluno NUMBER NOT NULL, PRIMARY KEY (id_turma, ra_aluno), 
  FOREIGN KEY (id_turma) REFERENCES notadez.turmas(id_turma), 
  FOREIGN KEY (ra_aluno) REFERENCES notadez.alunos(ra_aluno) );

-- Associação entre turmas e disciplinas
CREATE TABLE notadez.turma_disciplina ( 
  id_disciplina NUMBER NOT NULL, 
  id_turma NUMBER NOT NULL, PRIMARY KEY (id_disciplina, id_turma), 
  FOREIGN KEY (id_disciplina) REFERENCES notadez.disciplinas(id_disciplina), 
  FOREIGN KEY (id_turma) REFERENCES notadez.turmas(id_turma) );

-- ========================================
-- TRIGGERS DE AUDITORIA AUTOMÁTICA
-- ========================================

-- Trigger de atualização de notas: registra alteração de nota
create or replace trigger notadez.trigger_auditoria_notas_update 
before update on notadez.notas 
for each row 
begin 
    insert into notadez.auditoria_notas ( ra_aluno, id_componente, valor_antigo, valor_novo, id_docente, data_hora ) 
    values ( :old.ra_aluno, :old.id_componente, :old.valor_nota, :new.valor_nota, 1, systimestamp ); -- id_docente fixo, data atual
end; 
/

-- Trigger de inserção de notas: registra inserção de nova nota
create or replace trigger notadez.trigger_auditoria_notas_insert 
after insert on notadez.notas 
for each row 
begin 
    insert into notadez.auditoria_notas ( ra_aluno, id_componente, valor_antigo, valor_novo, id_docente, data_hora ) 
    values ( :new.ra_aluno, :new.id_componente, null, :new.valor_nota, 1, systimestamp ); -- id_docente fixo, data atual
end; 
/
