create user notadez identified by secretmypass;
grant connect,resource, create table, create view, create sequence, create trigger to notadez;
select username, authentication_type from dba_users where username = 'NOTADEZ'; /*da um select na tabela dba-users pra verificar se o usuario webapp foi criado*/
create tablespace data datafile 'C:\app\Usuario\product\21c\oradata\XE\data.dbf' size 100M autoextend on;

alter user notadez default tablespace 
  data temporary tablespace temp;

alter user notadez quota 100M on data; /* altera para ter 100 megas de dados*/

select username, default_tablespace, temporary_tablespace from dba_users where username = 'NOTADEZ'; /* verificar se o usuario webapp esta la, e qual o tablespace temporario*/

select tablespace_name, bytes, max_bytes from dba_ts_quotas where username = 'NOTADEZ'; /*VERIFICAR A QUOTA/ /ainda como admin vamos criar uma tabela*/

create table NOTADEZ.DOCENTES (
   ID_DOCENTE    number generated by default as identity primary key,
   NOME  varchar2(100) not null,
   EMAIL varchar2(100) unique,
   SENHA varchar2(100) not null,
   TELEFONE int,
   DATA_CADASTRO date default current_date
)
tablespace data; /*regra para que cada espaço de tabela tenha um dado guardado, tipo NOT NULL*/

select * from NOTADEZ.DOCENTES;

CREATE TABLE notadez.turmas ( 
  id_turma NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  nome_turma VARCHAR2(100) NOT NULL, 
  horario_aula TIMESTAMP NOT NULL, -- Oracle TIMESTAMP armazena data e hora 
  local_aula VARCHAR2(100) NOT NULL, 
  dia_aula VARCHAR2(20) NOT NULL );

CREATE TABLE notadez.disciplinas ( 
  id_disciplina NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  sigla_disciplina VARCHAR2(20) NOT NULL, 
  nome_disciplina VARCHAR2(100) NOT NULL, 
  periodo DATE NOT NULL ,-- TIME nao e um tipo nativo 
  DATE --armazena data e hora 
  );

CREATE TABLE notadez.instituicoes ( 
  id_instituicao NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  nome_instituicao VARCHAR2(100) NOT NULL );

CREATE TABLE notadez.cursos ( 
  id_curso NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  nome_curso VARCHAR2(100) NOT NULL, 
  id_instituicao NUMBER NOT NULL, 
  FOREIGN KEY (id_instituicao) REFERENCES notadez.instituicoes(id_instituicao) );

CREATE TABLE notadez.notas ( 
  id_nota NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  id_turma NUMBER NOT NULL, 
  valor_nota NUMBER NOT NULL, -- FLOAT e sinonimo de NUMBER 
  data_lancamento DATE NOT NULL, 
  FOREIGN KEY (id_turma) REFERENCES notadez.turmas(id_turma) );

CREATE TABLE notadez.alunos ( 
  ra_aluno NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  nome_aluno VARCHAR2(100) NOT NULL );

CREATE TABLE notadez.componentes_nota ( 
  id_componente NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  id_disciplina NUMBER NOT NULL, 
  nome_componente VARCHAR2(100) NOT NULL, 
  descricao VARCHAR2(255) NOT NULL, 
  sigla_componente VARCHAR2(20) NOT NULL, 
  FOREIGN KEY (id_disciplina) REFERENCES notadez.disciplinas(id_disciplina) );

CREATE TABLE notadez.formula_nota_final ( 
  id_formula NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  id_disciplina NUMBER NOT NULL, 
  tipo_formula VARCHAR2(50) NOT NULL, 
  peso_p1 NUMBER NOT NULL, 
  peso_p2 NUMBER NOT NULL, 
  peso_p3 NUMBER NOT NULL, 
  formula_text VARCHAR2(255) NOT NULL, 
  FOREIGN KEY (id_disciplina) REFERENCES notadez.disciplinas(id_disciplina) );

CREATE TABLE notadez.auditoria_notas ( 
  id_auditoria NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  ra_aluno NUMBER NOT NULL,
  id_componente NUMBER NOT NULL, 
  id_docente NUMBER NOT NULL, 
  valor_antigo NUMBER NOT NULL, 
  valor_novo NUMBER NOT NULL, 
  data_hora TIMESTAMP NOT NULL, -- Oracle TIMESTAMP para data e hora 
  FOREIGN KEY (ra_aluno) REFERENCES notadez.alunos(ra_aluno), 
  FOREIGN KEY (id_componente) REFERENCES notadez.componentes_nota(id_componente), 
  FOREIGN KEY (id_docente) REFERENCES notadez.docentes(id_docente) );

-- Tabelas Associativas (muitos-para-muitos)

CREATE TABLE notadez.cadastro ( 
  id_docente NUMBER NOT NULL, 
  id_instituicao NUMBER NOT NULL, PRIMARY KEY (id_docente, id_instituicao), 
  FOREIGN KEY (id_docente) REFERENCES notadez.docentes(id_docente), 
  FOREIGN KEY (id_instituicao) REFERENCES notadez.instituicoes(id_instituicao) );

CREATE TABLE notadez.matriculam ( 
  id_turma NUMBER NOT NULL, 
  ra_aluno NUMBER NOT NULL, PRIMARY KEY (id_turma, ra_aluno), 
  FOREIGN KEY (id_turma) REFERENCES notadez.turmas(id_turma), 
  FOREIGN KEY (ra_aluno) REFERENCES notadez.alunos(ra_aluno) );

CREATE TABLE notadez.turma_disciplina ( 
  id_disciplina NUMBER NOT NULL, 
  id_turma NUMBER NOT NULL, PRIMARY KEY (id_disciplina, id_turma), 
  FOREIGN KEY (id_disciplina) REFERENCES notadez.disciplinas(id_disciplina), 
  FOREIGN KEY (id_turma) REFERENCES notadez.turmas(id_turma) );

--Trigger para auditoria automatica - 
  UPDATE/ create or replace trigger notadez.trigger_auditoria_notas_update 
  before update on notadez.notas for each row begin insert into 
  notadez.auditoria_notas ( ra_aluno, id_componente, valor_antigo, valor_novo, id_docente ) 
  values ( :old.ra_aluno, :old.id_componente, :old.valor_nota, :new.valor_nota, 1 ); end; /

/Trigger para auditoria automatica - 
  INSERT/ create or replace trigger notadez.trigger_auditoria_notas_insert 
  after insert on notadez.notas for each row begin insert into 
  notadez.auditoria_notas ( ra_aluno, id_componente, valor_antigo, valor_novo, id_docente ) 
  values ( :new.ra_aluno, :new.id_componente, null, :new.valor_nota, 1 ); end; /

